version: "2"

# note: no paralleltest because we test operating system environment variables

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - gocritic
    - makezero
    - misspell
    - musttag
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - usetesting
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    presets:
      - comments
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
